### PR TITLE
Handle no elevations returned

### PR DESCRIPTION
**Pull request by th3w4y**
https://github.com/PokemonGoF/PokemonGo-Bot/pull/5184
https://github.com/Anakin5/PokemonGo-Bot/pull/6

### CODE REVIEW

**Comment by th3w4y** [comment]
```
test_bigger_then_total_speed (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... ok
test_bigger_then_total_speed_big_precision_offset (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... ok
test_intermediary_speed (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... ok
test_intermediary_speed_big_precision (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... ok
test_one_small_speed (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... ok
test_one_small_speed_big_precision (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... ok
test_polyline_fetched (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... ok
test_stay_put (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... ok
test_teleport (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... ok

----------------------------------------------------------------------
Ran 9 tests in 0.415s

OK
```

**Comment by th3w4y** [comment]
CI would pass
https://travis-ci.org/th3w4y/PokemonGo-Bot/builds/158261132

**Comment by Anakin5** [comment]
I modified the expected location in one test case that was randomly failing because the expected location was not precise enough.
I put back your formula for get_alt.
Let me if it is fine for you in the other thread.

**Comment by th3w4y** [comment]
Cool 👍 

(Actually i also did not correctly formulate my arguments I suck at that!)

>Sorry I did not understood at first that you got more points for altitude than for directions. So I understand better why you want to apply the relative formula directly in get_alt.

**Pull request merged**
