### PR TITLE
StepWalker test cases

### PR DESCRIPTION
**Pull request by th3w4y**
test cases for #5184

### CODE REVIEW

**Comment by Anakin5** [comment]
For the speed float(inf), I removed it on purpose because the code was valid without it. dist will be equal to total_distance and the new position will be the destination.

**Comment by th3w4y** [comment]
yes it looked right at first... until i wrote the test case... 
then it was returning False... from is_arrived()

>For the speed float(inf), I removed it on purpose because the code was valid without it. dist will be equal to total_distance and the new position will be the destination.

**Comment by Anakin5** [comment]
I am facing big issues with imprecision from vincenty and haversine.
I started to switch everything to vincenty, but it not enough for long distances.
I am switching now to geographiclib which can already compute bearing and distances for us.

**Comment by th3w4y** [comment]
VincentyDistance works only for small distances <1KM

that is why the special case for teleport

**Comment by th3w4y** [comment]
@Anakin5 i could figure out fast how to cal bearings with the geographiclib.. i was lazy and choose the VincentyDistance...

I can hardly wait to see how the greographiclib handles that...

**Comment by th3w4y** [comment]
@Anakin5 I actually saw I made a mistake in my commit regarding the float("inf") part i was setting self.precision to inf("")  should work without that...

that was ugly hack... to make the test case pass 

I just realised that the test_case don't properly mock the bot.position and is_arrived() does not return correct...

I will look into mocking the bot.position

**Comment by Anakin5** [comment]
wait, I fixed it already

**Comment by Anakin5** [comment]
For now the Polyline is completely broken, but I commit so that you can see where I am.

**Comment by th3w4y** [comment]
I was fixing the test like this... https://github.com/Anakin5/PokemonGo-Bot/pull/4

**Comment by th3w4y** [comment]
@Anakin5 do not override haversine with distance :(

**Comment by Anakin5** [comment]
What do you mean ?

**Comment by th3w4y** [comment]
:)) too much code change to follow at this time...

**Comment by Anakin5** [comment]
Ignore the utils, I will roll it back

**Comment by th3w4y** [comment]
@Anakin5 i have to travel to work now talk soon

**Comment by th3w4y** [comment]
skimmed  through should have worked...
what broke on the Polyline?

**Comment by th3w4y** [comment]
exceot the removal of encode(cellid) wasn't that used in transforming forts s2sphere location to lat, lng?

**Comment by Anakin5** [comment]
the get_next_pos is still using haversine and doing mostly the same as StepWalker get_next_postion only in more horrible way.
I am removing the get_next_pos from polyline to put it in PolylineWalker to reused the code of StepWalker.

**Comment by th3w4y** [comment]
I suggest to not remove it... copy the same code from StepWalker if you have to...

**Comment by th3w4y** [comment]
@Anakin5  you re refiguring to this?

```
    def _calc_next_pos(self, origin, distance, bearing):
        lat, lng, _ = origin
        if distance == 0.0:
            return lat, lng
        if distance == float("inf"):
            return self.destination
        lat, lng, _ = VincentyDistance(kilometers=distance * 1e-3).destination(origin, bearing)
        return (lat, lng)

```

**Comment by Anakin5** [comment]
This yes, and _calc_bearing and get_pos

**Comment by th3w4y** [comment]
what do you want to do with get_pos? If you move it around:

- Polyline will remain just a dummy container of points and elevations is this what you want?
- you'll have to handle the move on the polyline from the PolylineWalker?
- will break all polyline generator test cases :)

**Comment by Anakin5** [comment]
Mostly yes:
- Yes polyline will just be a container of point. It also hold the state of what point we already passed by
- Yes but in PolylineWalker I can get the next position in 20 lines of code instead of 200 in Polyline
- Yes, we have to get new test cases :)

**Comment by th3w4y** [comment]
@Anakin5 I have a compromise solution:

since you will need to handle the polyline._last_pos in PolylineWalker in your approach... 


do not remove  .get_pos() in Polyline for now

you should what you want by handling:  ._last_pos and ._last_step in the PolylineWalker..  you will just not use .get_pos() right....

then i'll write some test to compare...

**Comment by th3w4y** [comment]
200 code in Polyline are handling corner... if you understand what i meant...


>Yes but in PolylineWalker I can get the next position in 20 lines of code instead of 200 in Polyline

**Comment by th3w4y** [comment]
This walks in baby steps all the corners and stuff.. until is somewhere on a walk_dict_step...

how do you plan to do that in less code?

```
        while haversine.haversine(self._last_pos, (sd_lat, sd_lng))*1000 < distance:
            distance -= haversine.haversine(self._last_pos, (sd_lat, sd_lng))*1000
            self._last_pos = (sd_lat, sd_lng)
            if self._last_step < len(self._step_keys)-1:
                self._last_step += 1
                ((so_lat, so_lng), (sd_lat, sd_lng)) = self._step_dict[self._step_keys[self._last_step]]
                bearing = self._calc_bearing(so_lat, so_lng, sd_lat, sd_lng)
                origin = Point(so_lat, so_lng)
                lat, lng = self._calc_next_pos(origin, distance, bearing)
                if haversine.haversine(self._last_pos, (lat, lng))*1000 < distance:
                    distance -= haversine.haversine(self._last_pos, (lat, lng))*1000
                    self._last_pos = (lat, lng)
            else:
                return self.get_last_pos()
        else:
            lat, lng = self._calc_next_pos(origin, distance, bearing)
            self._last_pos = (lat, lng)
            return self.get_last_pos()
```

**Comment by th3w4y** [comment]
You cannot simply take the next point... based on the bearing to destination what heading would that have?

**Comment by th3w4y** [comment]
I tried a striped no alt version of the PolylineWalker logic inside the Polyline with the old .get_pos() name just to not modify the tests at all..

I believe is same logic but did not spent to much time

```
    def set_speed(self, speed):
        self.speed = speed

    def get_pos(self):

        distance = self.speed
        while True:
            origin, destination = self._step_dict[self._step_keys[self._last_step]]
            next_lat, next_lng = self._get_next_position(origin, destination, self.speed)
            if self._last_step == len(self._step_keys) - 1:
                break
            else:
                travelled = Geodesic.WGS84.Inverse(origin[0], origin[1], next_lat, next_lng)["s12"]
                remaining = Geodesic.WGS84.Inverse(next_lat, next_lng, destination[0], destination[1])["s12"]
                step_distance = Geodesic.WGS84.Inverse(origin[0], origin[1], destination[0], destination[1])["s12"]

                if remaining < 1e-2:
                    self._last_step += 1
                    distance = abs(distance - step_distance)
                else:
                    distance = abs(distance - travelled)

                if distance > 1e-2:
                    origin = destination
                else:
                    break

        self._last_pos = (next_lat, next_lng)

        return (next_lat, next_lng)
    

    def _get_next_position(self, origin, destination, distance):
        orig_lat, orig_lng = origin
        dest_lat, dest_lng = destination
        inverse = Geodesic.WGS84.Inverse(orig_lat, orig_lng, dest_lat, dest_lng)
        direct = Geodesic.WGS84.Direct(orig_lat, orig_lng, inverse["azi1"], distance)
        return (direct["lat2"], direct["lon2"])
```

**Comment by th3w4y** [comment]
now above code with speed 17.5m/s like in the testcases... is 392m of then the expected destination in test case.

**Comment by Anakin5** [comment]
We should adapt the test case to the code. Polyline is better without the code to compute the next step, that is no its responsibility.
We do not need to keep the old test cases, we can get new ones.

**Comment by th3w4y** [comment]
We should keep this ones:

test_first_point (pokemongo_bot.test.polyline_generator_test.PolylineTestCase) ... ok
test_get_last_pos (pokemongo_bot.test.polyline_generator_test.PolylineTestCase) ... ok
test_last_point (pokemongo_bot.test.polyline_generator_test.PolylineTestCase) ... ok
test_nr_of_elevations_returned (pokemongo_bot.test.polyline_generator_test.PolylineTestCase) ... ok
test_total_distance (pokemongo_bot.test.polyline_generator_test.PolylineTestCase) ... ok

**Comment by Anakin5** [comment]
Do you have code to make them pass ?

**Comment by th3w4y** [comment]
those are non positional test inly checking nr elevations and do not rely on the removed .get_pos()

**Comment by th3w4y** [comment]
i want to re-add the .get_pos() to have the teoretical position at speed x from start to end without modifying the self._last_pos
then later we can compare how much is PolylineWalker of from the teoretical...

**Comment by Anakin5** [comment]
I don't understand, getting the final position is not that simple and it is what is written in get_next_position. So you want to write another function that does the same to check whether the first one works ? Do you have another method to compute that final position ?

**Comment by Anakin5** [comment]
We would first write test that give a distance which is one of the steps, so that checking the result is easier since it is just making sure we are equal to the sum of the steps.

**Comment by th3w4y** [comment]
@Anakin5 I know it took me about 2h to get the old get_pos right :(


```
    def get_pos(self):
        if self.speed > self.get_total_distance():
            self._last_pos = self.destination
            self._last_step = len(self._step_keys)-1
        if self.get_last_pos() == self.destination:
            return self.get_last_pos()
        distance = self.speed
        origin = Point(*self._last_pos)
        ((so_lat, so_lng), (sd_lat, sd_lng)) = self._step_dict[self._step_keys[self._last_step]]
        bearing = self._calc_bearing(so_lat, so_lng, sd_lat, sd_lng)
        while haversine.haversine(self._last_pos, (sd_lat, sd_lng))*1000 < distance:
            distance -= haversine.haversine(self._last_pos, (sd_lat, sd_lng))*1000
            self._last_pos = (sd_lat, sd_lng)
            if self._last_step < len(self._step_keys)-1:
                self._last_step += 1
                ((so_lat, so_lng), (sd_lat, sd_lng)) = self._step_dict[self._step_keys[self._last_step]]
                bearing = self._calc_bearing(so_lat, so_lng, sd_lat, sd_lng)
                origin = Point(so_lat, so_lng)
                lat, lng = self._calc_next_pos(origin, distance, bearing)
                if haversine.haversine(self._last_pos, (lat, lng))*1000 < distance:
                    distance -= haversine.haversine(self._last_pos, (lat, lng))*1000
                    self._last_pos = (lat, lng)
            else:
                return self.get_last_pos()
        else:
            lat, lng = self._calc_next_pos(origin, distance, bearing)
            self._last_pos = (lat, lng)
            return self.get_last_pos()
```

**Comment by Anakin5** [comment]
What do you think about my proposal of checking Polyline points first. And they from there we look what we are missing to test in between location ?

**Comment by th3w4y** [comment]
@Anakin5 the are already tests for the polyline points those are done... and are passing

~~Regarding the second part i still have to take a closer look on your method of calculation and why that was 392m off at the 17.5m speed when i tried to "brutto" replicate it... ~~ (I cut out this part as i am not 100% sure)

**Comment by Anakin5** [comment]
Can you print the length of each segment of that Polyline and the number of the step we reach ? That way we could at least see if the result is coherent or not.

**Comment by th3w4y** [comment]
@Anakin5 so far i was going through the code and was wondering did you also changed .get_alt()?

**Comment by Anakin5** [comment]
not changed

**Comment by th3w4y** [comment]
But i see you did not You did

then...

https://github.com/Anakin5/PokemonGo-Bot/blob/43b860864a6e302a3355a4d459a11c662e0182d8/pokemongo_bot/walkers/polyline_walker.py#L13

`dest_alt = polyline.get_alt() or origin_alt`

since you do not update self._last_pos until the end you will always get the altitude at the origin

**Comment by th3w4y** [comment]
Solution: 

either change .get_alt(self, point)
or update polyline._self_pos when step is walked...

**Comment by Anakin5** [comment]
I like the first

**Comment by th3w4y** [comment]
I like the second... and let me tell you why...

The polyline gets invalidated if you are to far away from self._last_pos when you reinitialise a PolylineWalker object!

**Comment by th3w4y** [comment]
I repeat myself but currently this PolylineWalkers and PolylineSteppers are volatile... they get recreated on every .work()

**Comment by th3w4y** [comment]
offset now is 8m!

**Comment by Anakin5** [comment]
The polylineWalker work now without need to be recreated. I am using it like that in CampFort. We can even get the polyline only one time in init.

**Comment by th3w4y** [comment]
@Anakin5 this is not the case for other workers.. there are still workers with create it on every .work()

**Comment by Anakin5** [comment]
Yes we can just update them. I mean it is completely over engineered, all that cache management to store polyline just because we keep on recreating object for no good reason.
We should keep it simple unless you we have a very good reason, above all, to recreate these objects each time.

**Comment by th3w4y** [comment]
It should be in the BaseTask

base task should import walker_factory and instantiate the configured stepper...

**Comment by th3w4y** [comment]
be probably need TASK_API_VERSION = 1.2 :)

**Comment by th3w4y** [comment]
.. those tests can be removed... 

https://github.com/Anakin5/PokemonGo-Bot/pull/4

**Comment by th3w4y** [comment]
i wrote test cases for the PolylineWalker... https://github.com/Anakin5/PokemonGo-Bot/pull/4/commits/b6cb5f3f2fdcce43936dc60ae6849c054f18839c

All the altitude calculation are failing as discussed..


speed 166m/s precision=0.01 epsilon =0.01 traveled speed 2m :)

**Comment by th3w4y** [comment]
300m/s test_bigger_then_total_speed (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... total-distance -0.00270945663929 compared to precision+epsilon 0.02 
FAIL
166m/s test_intermediary_speed (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... total-distance -2.66567291429 compared to precision+epsilon 0.02 
FAIL

0.24m/s test_small_speed (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... total-distance 0.0416643855338 compared to precision+epsilon 0.02 
FAIL
test_stay_put (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... FAIL
test_teleport (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... FAIL
test_polyline_fetched (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... ok


======================================================================
FAIL: test_bigger_then_total_speed (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oghinet/Checkout/public/PokemonGo-Bot/pokemongo_bot/test/polyline_walker_test.py", line 162, in test_bigger_then_total_speed
    self.assertAlmostEqual(self.polyline.get_alt(), self.bot.position[2])
AssertionError: 437.9155883789062 != 429.723018059962 within 7 places

======================================================================
FAIL: test_intermediary_speed (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oghinet/Checkout/public/PokemonGo-Bot/pokemongo_bot/test/polyline_walker_test.py", line 128, in test_intermediary_speed
    self.assertTrue(0.0 <= abs(total_distance - distance) <= (pw.precision + pw.epsilon))
AssertionError: False is not true

======================================================================
FAIL: test_small_speed (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oghinet/Checkout/public/PokemonGo-Bot/pokemongo_bot/test/polyline_walker_test.py", line 96, in test_small_speed
    self.assertTrue(0.0 <= abs(total_distance - distance) <= (pw.precision + pw.epsilon))
AssertionError: False is not true

======================================================================
FAIL: test_stay_put (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oghinet/Checkout/public/PokemonGo-Bot/pokemongo_bot/test/polyline_walker_test.py", line 189, in test_stay_put
    self.assertAlmostEqual(self.polyline.get_alt(), self.bot.position[2])
AssertionError: 429.5892333984375 != -0.05107640239230227 within 7 places

======================================================================
FAIL: test_teleport (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oghinet/Checkout/public/PokemonGo-Bot/pokemongo_bot/test/polyline_walker_test.py", line 216, in test_teleport
    self.assertAlmostEqual(self.polyline.get_alt(), self.bot.position[2])
AssertionError: 437.9155883789062 != 429.5815512784267 within 7 places

----------------------------------------------------------------------
Ran 6 tests in 0.701s

FAILED (failures=5)
(pokemon) ✘-1 ~/Checkout/public/PokemonGo-Bot [patch-2|✔] 
22:05 $

**Comment by th3w4y** [comment]
test_bigger_then_total_speed (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... distance: 0.00623891395439 p+e:0.02 speed: 300 
FAIL
test_bigger_then_total_speed_big_precision_offset (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... distance: 0.262201699784 p+e:2.51 speed: 300 
FAIL
test_intermediary_speed (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... distance: 6.82329262192 p+e:0.02 speed: 166.828517235 
FAIL
test_intermediary_speed_big_precision (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... distance: 7.63248044718 p+e:2.51 speed: 166.828517235 
FAIL
test_one_small_speed (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... distance: 0.0447710811787 p+e:0.02 speed: 0.2 
FAIL
test_one_small_speed_big_precision (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... distance: 0.658878075113 p+e:2.51 speed: 0.2 
FAIL
test_polyline_fetched (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... ok
test_stay_put (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... distance: 121.712602787 p+e:0.02 speed: 0.0 
FAIL
test_teleport (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker) ... distance: 0.00626165683526 p+e:0.02 speed: inf 
FAIL

======================================================================
FAIL: test_bigger_then_total_speed (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oghinet/Checkout/public/PokemonGo-Bot/pokemongo_bot/test/polyline_walker_test.py", line 229, in test_bigger_then_total_speed
    self.assertTrue(speed - (pw.precision + pw.epsilon) <= distance <= speed + (pw.precision + pw.epsilon))
AssertionError: False is not true

======================================================================
FAIL: test_bigger_then_total_speed_big_precision_offset (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oghinet/Checkout/public/PokemonGo-Bot/pokemongo_bot/test/polyline_walker_test.py", line 263, in test_bigger_then_total_speed_big_precision_offset
    self.assertTrue(speed - (pw.precision + pw.epsilon) <= distance <= speed + (pw.precision + pw.epsilon))
AssertionError: False is not true

======================================================================
FAIL: test_intermediary_speed (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oghinet/Checkout/public/PokemonGo-Bot/pokemongo_bot/test/polyline_walker_test.py", line 164, in test_intermediary_speed
    self.assertTrue(speed - (pw.precision + pw.epsilon) <= distance <= speed + (pw.precision + pw.epsilon))
AssertionError: False is not true

======================================================================
FAIL: test_intermediary_speed_big_precision (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oghinet/Checkout/public/PokemonGo-Bot/pokemongo_bot/test/polyline_walker_test.py", line 196, in test_intermediary_speed_big_precision
    self.assertTrue(speed - (pw.precision + pw.epsilon) <= distance <= speed + (pw.precision + pw.epsilon))
AssertionError: False is not true

======================================================================
FAIL: test_one_small_speed (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oghinet/Checkout/public/PokemonGo-Bot/pokemongo_bot/test/polyline_walker_test.py", line 98, in test_one_small_speed
    self.assertTrue(speed - (pw.precision + pw.epsilon) <= distance <= speed + (pw.precision + pw.epsilon))
AssertionError: False is not true

======================================================================
FAIL: test_one_small_speed_big_precision (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oghinet/Checkout/public/PokemonGo-Bot/pokemongo_bot/test/polyline_walker_test.py", line 133, in test_one_small_speed_big_precision
    self.assertAlmostEqual(self.polyline.get_alt(), self.bot.position[2])
AssertionError: 429.5892333984375 != 347.0863296768779 within 7 places

======================================================================
FAIL: test_stay_put (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oghinet/Checkout/public/PokemonGo-Bot/pokemongo_bot/test/polyline_walker_test.py", line 288, in test_stay_put
    self.assertTrue(0.0 <= distance <= (pw.precision + pw.epsilon))
AssertionError: False is not true

======================================================================
FAIL: test_teleport (pokemongo_bot.test.polyline_walker_test.TestPolylineWalker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oghinet/Checkout/public/PokemonGo-Bot/pokemongo_bot/test/polyline_walker_test.py", line 312, in test_teleport
    self.assertTrue(0.0 <= abs(total_distance - distance) <= (pw.precision + pw.epsilon))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 9 tests in 1.125s

FAILED (failures=8)

**Comment by th3w4y** [comment]
@Anakin5 good work the calculation were correct after all! (I was doing a mistake when checking...)

**Pull request merged**
